---
kind: pipeline
type: docker
name: php-fpm-74

platform:
  os: linux
  arch: amd64

steps:
- name: php-fpm-74
  image: plugins/docker
  settings:
    repo: joseluisq/php
    dockerfile: ./7.4-fpm/Dockerfile
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    tags:
      - "7"
      - "7.4"
      - "fpm"
      - "fpm-7"
      - "fpm-7.4"

trigger:
  target:
  - php-fpm-74

---
kind: pipeline
type: docker
name: notification

platform:
  os: linux
  arch: amd64

steps:
- name: notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: ci-cd

depends_on:
- php-fpm-74

trigger:
  status:
  - success
  - failure
