---
kind: pipeline
type: docker
name: production

platform:
  os: linux
  arch: amd64

steps:
- name: php-fpm
  image: plugins/docker
  settings:
    repo: joseluisq/php
    dockerfile: ./php-fpm/Dockerfile
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    tags:
      - "7"
      - "7.4"
    auto_tag_suffix: fpm

trigger:
  target:
  - production


---
kind: pipeline
type: docker
name: notification

platform:
  os: linux
  arch: amd64

steps:
- name: notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: ci-cd

depends_on:
- production

trigger:
  status:
  - success
  - failure
