---
kind: pipeline
type: docker
name: development-php74

platform:
  os: linux
  arch: amd64

steps:
- name: build-php74
  image: docker
  failure: ignore
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
    - echo "Building alpine-php-fpm:php74 image..."
    - docker build -t alpine-php-fpm:php74 -f 7.4-fpm/Dockerfile .

- name: test-php74
  image: alpine-php-fpm:php74
  failure: ignore
  pull: if-not-exists
  commands:
    - ./7.4-fpm/php_fpm_test.sh

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

trigger:
  event:
    - push
    - pull_request
  branch:
    - master
    - develop
    - feature/*
    - bugfix/*
    - hotfix/*



---
kind: pipeline
type: docker
name: development-php80

platform:
  os: linux
  arch: amd64

steps:
- name: build-php80
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
    - echo "Building alpine-php-fpm:php80 image..."
    - docker build -t alpine-php-fpm:php80 -f 8.0-fpm/Dockerfile .

- name: test-php80
  image: alpine-php-fpm:php80
  pull: if-not-exists
  commands:
    - ./8.0-fpm/php_fpm_test.sh

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

trigger:
  event:
    - push
    - pull_request
  branch:
    - master
    - develop
    - feature/*
    - bugfix/*
    - hotfix/*



---
kind: pipeline
type: docker
name: production-php74

platform:
  os: linux
  arch: amd64

steps:
- name: php-fpm-74
  image: joseluisq/drone-docker
  privileged: true
  settings:
    repo: joseluisq/php-fpm
    dockerfile: ./7.4-fpm/Dockerfile
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    auto_tag: true

trigger:
  ref:
    include:
    - refs/tags/v7.4*



---
kind: pipeline
type: docker
name: production-php80

platform:
  os: linux
  arch: amd64

steps:
- name: php-fpm-80
  image: joseluisq/drone-docker
  privileged: true
  settings:
    repo: joseluisq/php-fpm
    dockerfile: ./8.0-fpm/Dockerfile
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    auto_tag: true
    auto_tag_aliases:
      - "latest"

trigger:
  ref:
    include:
    - refs/tags/v8.0*



---
kind: pipeline
type: docker
name: notification

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: ci-cd

depends_on:
- development-php74
- development-php80
- production-php74
- production-php80

trigger:
  status:
  - success
  - failure
