language: minimal

services:
  - docker

notifications:
  email: false

git:
  depth: 1

jobs:
  fast_finish: true
  allow_failures:
  - name: "php 7.4"
  include:
  - name: "php 8.0"
    env: DOCKER_PHP_VERSION=8.0
  - name: "php 7.4"
    env: DOCKER_PHP_VERSION=7.4

script:
  - echo "Building alpine-php-fpm:php$DOCKER_PHP_VERSION image..."
  - docker build -t alpine-php-fpm:php$DOCKER_PHP_VERSION -f $DOCKER_PHP_VERSION-fpm/Dockerfile .
  - docker run --rm -v $PWD/$DOCKER_PHP_VERSION-fpm/:/var/www/share/project -w /var/www/share/project alpine-php-fpm:php$DOCKER_PHP_VERSION ./php_fpm_test.sh
