name: release-v7.4
on:
  push:
    tags:
    - 'v7.4.[0-9]+'
    - 'v7.4.[0-9]+-beta.[0-9]+'

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: joseluisq/php-fpm
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/386
          # platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6
          file: 7.4-fpm/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
